"""Weekly summary export — Markdown download."""

import json
from datetime import datetime

import streamlit as st

from api_client import api_get
from constants import CATEGORY_LABELS, URGENCY_LABELS


def build_weekly_markdown(data: dict) -> str:
    username = data.get("username", "User")
    week_start = data["week_start"]
    week_end = data["week_end"]
    stats = data.get("stats", {})
    lines = [
        f"# Weekly Productivity Summary — {username}",
        f"",
        f"**Week:** {week_start} to {week_end}",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"",
        f"## Overview",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Check-in streak | {stats.get('streak', 0)} day(s) |",
        f"| Total tasks | {stats.get('total_tasks', 0)} |",
        f"| Completed | {stats.get('completed', 0)} |",
        f"| Skipped | {stats.get('skipped', 0)} |",
        f"| Completion rate | {stats.get('completion_rate', 0)}% |",
        f"",
    ]

    cats = stats.get("by_category", {})
    if cats:
        lines += ["## Tasks by category", ""]
        for cat, count in sorted(cats.items(), key=lambda x: -x[1]):
            label = CATEGORY_LABELS.get(cat, cat.capitalize())
            lines.append(f"- **{label}:** {count}")
        lines.append("")

    daily = stats.get("daily_completion", [])
    if daily:
        lines += ["## Daily completion", ""]
        for d in daily:
            if d["total"] > 0:
                lines.append(
                    f"- **{d['date']}:** {d['completed']}/{d['total']} tasks ({d['completion_rate']}%)"
                )
        lines.append("")

    eods = data.get("eod_summaries", [])
    if eods:
        lines += ["## Daily summaries", ""]
        for e in eods:
            lines += [f"### {e['summary_date']}", "", e["summary_text"], ""]
            if e.get("tomorrow_plan"):
                try:
                    plan = json.loads(e["tomorrow_plan"])
                    if plan:
                        lines.append("**Tomorrow's plan was:**")
                        for item in plan:
                            lines.append(f"- {item}")
                        lines.append("")
                except (json.JSONDecodeError, TypeError):
                    pass

    tasks = data.get("tasks", [])
    if tasks:
        lines += ["## All tasks this week", ""]
        current_date = None
        for t in tasks:
            if t["due_date"] != current_date:
                current_date = t["due_date"]
                lines += [f"### {current_date}", ""]
            urg = URGENCY_LABELS.get(t.get("urgency", "medium"), "")
            cat = CATEGORY_LABELS.get(t.get("category", "other"), t.get("category", ""))
            if t.get("completed_at"):
                status = "done"
            elif t.get("skipped"):
                status = "skipped"
            else:
                status = "pending"
            lines.append(f"- [{status}] {t['title']} ({cat}, {urg})")
        lines.append("")

    review = data.get("weekly_review")
    if review:
        lines += ["## Weekly review", "", review["review_text"], ""]

    lines.append("---")
    lines.append("*Generated by Personal Productivity Agent*")
    return "\n".join(lines)


def render_export_buttons():
    """Download button — reusable from Dashboard or This Week."""
    resp = api_get("/analytics/export/week")
    if resp.status_code != 200:
        st.warning("Couldn't prepare export.")
        return

    data = resp.json()
    md_content = build_weekly_markdown(data)
    filename = f"weekly_summary_{data['week_start']}.md"

    st.download_button(
        label="Download Weekly Summary (Markdown)",
        data=md_content,
        file_name=filename,
        mime="text/markdown",
        type="primary",
        use_container_width=True,
    )

    with st.expander("Preview export"):
        st.markdown(md_content)


def show_export():
    st.header("Export Reports")
    st.caption("Download your weekly productivity summary to share with a client or manager.")
    render_export_buttons()
